ITS QC FEE task without data sampling
AliceO2Group/ControlWorkflows pull request #122
Opened 2021-09-14 13:44 UTC by JianLIUhep

- ITS QC FEE task without data sampling
- Validated with FLP suite v0.27.0 at P2

2021-09-16 07:10 UTC, knopers8 requested changes
Hi, it's seems all good, but please also add the two new scripts to `generate-all-dpl-workflows.sh`

2021-09-17 12:18 UTC, JianLIUhep commented
Sorry for my late action. the scripts added to `generate-all-dpl-workflows.sh`

2021-09-17 12:21 UTC, knopers8 approved these changes

2021-09-17 12:21 UTC, knopers8 commented
Thanks!

2021-09-17 12:21 UTC, merged