[OCTRL-498] [WIP] Parallel phos workflows
AliceO2Group/ControlWorkflows pull request #82
Opened 2021-06-15 14:47 UTC by Barthelemy

2021-06-16 09:37 UTC, Barthelemy commented
Why is there an error for hmpid task that I did not touch ?

2021-06-16 12:19 UTC, knopers8 commented
CI doesn't work, this is not a problem with your PR. Reviewing it now

2021-06-16 12:41 UTC, knopers8 requested changes
Thank you for the templates and the doc. There are minor things to be fixed/added.

Please also add the three new scripts to `scripts/generate-all-dpl-workflows.sh`

2021-06-16 12:41 UTC, knopers8 commented on README.md
> +3. Access a FLP with the proper FLP Suite
```suggestion
3. Access an FLP with the proper FLP Suite
```

2021-06-16 12:41 UTC, knopers8 commented on scripts/phos-compressor-raw-qcmnt3.sh
> +WF_NAME=phos-compressor-raw-qcmn-localt3
I would maybe use this name instead (or even `phos-compressort3-raw-qcmn-local` because the compressor is parallelized).. This way we also leave room for some automatization in GUI, if we always keep the `*-remote` and  `*-local` convention.

This will of course imply generating the templates again.
```suggestion
WF_NAME=phos-compressor-raw-qcmnt3-local
```

2021-06-16 12:41 UTC, knopers8 commented on scripts/phos-compressor-raw-qcmnt3.sh
> +WF_NAME=phos-compressor-raw-qcmn-remote
this will overwrite the non-parallel workflow, which is fine in principle, but perhaps won't be very clear. could you add `t3` here as well (in the same convention as for "local")?

2021-06-16 12:41 UTC, knopers8 commented on tasks/phos-compressor-raw-qc-Dispatcher.yaml
> +    rateLogging: "{{ fmq_rate_logging }}"
This and the other changes to tasks for `phos-compressor-raw-qc` are already there in `master`. I don't understand why github does not complain about merge conflicts to resolve.

2021-06-16 12:41 UTC, knopers8 commented on scripts/phos-compressor-raw-qcmnt3.sh
> +#!/usr/bin/env bash
Templates generated by this script are missing in the PR.

2021-06-16 14:54 UTC, Barthelemy commented on scripts/phos-compressor-raw-qcmnt3.sh
> +WF_NAME=phos-compressor-raw-qcmn-remote
correct, completely missed htis one.

2021-06-16 14:55 UTC, Barthelemy commented on tasks/phos-compressor-raw-qc-Dispatcher.yaml
> +    rateLogging: "{{ fmq_rate_logging }}"
I will regenerate any ways, let's see if it stays.

2021-06-16 14:55 UTC, Barthelemy commented on scripts/phos-compressor-raw-qcmnt3.sh
> +#!/usr/bin/env bash
yep, forgot to push the commit. Regenerating any ways.

2021-06-17 06:16 UTC, Barthelemy commented on tasks/phos-compressor-raw-qc-Dispatcher.yaml
> +    rateLogging: "{{ fmq_rate_logging }}"
the mystery stays: why does it mark it as new lines ?

2021-06-17 06:33 UTC, knopers8 commented on tasks/phos-compressor-raw-qc-Dispatcher.yaml
> +    rateLogging: "{{ fmq_rate_logging }}"
Could you rebase? For sure you don't have changes from the latest master in your branch.

2021-06-17 06:51 UTC, Barthelemy commented on tasks/phos-compressor-raw-qc-Dispatcher.yaml
> +    rateLogging: "{{ fmq_rate_logging }}"
yep, that's it

2021-06-17 07:13 UTC, knopers8 approved these changes

2021-06-17 07:15 UTC, merged

2021-06-18 13:48 UTC, knopers8 commented
@miltalex @teo Could you please bring this to the FLP v0.19.0 branch?

2021-06-18 13:49 UTC, miltalex commented
@knopers8 Yes I will do it now